name: Feature 추가합니다
description: 새로운 Feature를 추가합니다.
body:
  - type: markdown
    attributes:
      value: |
        새로운 Feature를 추가합니다.
        
        ---
  - type: input
    id: php
    attributes:
      label: PHP Version
      description: "Please provide the full PHP version that is powering Tinkerwell."
      placeholder: "PHP 8.0.7, built: Jun  4 2021 01:50:04"
    validations:
      required: true
  - type: textarea
    id: feat-description
    attributes:
      label: 작업할 내용
      description: 작업할 내용을 상세히 적어주세요
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: 스크린샷 혹은 gif
      description: "작업할 내용의 스크린샷 혹은 UX라면 gif를 추가해주세요"
      placeholder: "<img src='https://블라블라' width='300'>"
  - type: textarea
    id: todo
    attributes:
      label: TODO
      description: 해당 작업을 완료하기 위한 TODO 리스트를 작성해 주세요.
      placeholder: "- [ ] todo1"
    validations:
      required: true
